import '../../../core/result/result.dart';
import 'auth_models.dart';

abstract class AuthRepository {
  Future<Result<AuthUser>> signIn({
    required String emailOrUsername,
    required String password,
  });

  /// Begin MFA setup.
  ///
  /// SECURITY CONTRACT — do not violate:
  /// - The TOTP secret and the full `otpauth://` URI are generated by the
  ///   SERVER and returned here as opaque strings. The client never
  ///   generates a TOTP secret, does not know how it was derived, and
  ///   must not persist it beyond this widget's lifetime.
  /// - Backup codes are likewise issued by the server. The client only
  ///   displays them and offers a copy action.
  /// - A conforming real implementation of this repository must call
  ///   the backend and return the response as-is.
  Future<Result<MfaSetupData>> beginMfaSetup();

  Future<Result<void>> verifyMfa(String code);

  Future<Result<void>> requestPasswordReset(String email);

  Future<Result<void>> verifyResetOtp(String email, String code);

  Future<Result<void>> setNewPassword(String password);

  Future<Result<AuthUser?>> currentUser();

  Future<Result<void>> confirmNewDevice({required bool itsMe});

  Future<Result<void>> signOut();

  Future<Result<List<Session>>> listSessions();

  Future<Result<void>> revokeSession(String id);
}
